package mylib;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int addIntegers(int x, int y) {
        System.out.println("HEHHEHHE");
        return x * y;
    }
}
